data:
  input_file: "data/input_trace.txt"
  output_file: "data/generated_trace.txt"

model:
  latent_dim: 10
  generator_hidden_dim: 64
  discriminator_hidden_dim: 64
  sequence_length: 50

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0002
  beta1: 0.5

evaluation:
  mmd: true
  replay: true
